version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: rated-movies
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: rated_movies_db
    ports:
      - "5432:5432"
