CREATE TYPE MOVIE_CATEGORY_ENUM AS ENUM (
'ACTION', 'ADVENTURE', 'ANIMATION', 'COMEDY', 'DOCUMENTARY', 'DRAMA', 'HORROR_MOVIE', 'ROMANCE', 'ROMANTIC_COMEDY',
  'SCIFI', 'SUPERHERO');

CREATE TABLE movie (
    id UUID PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    year INTEGER NOT NULL,
    category MOVIE_CATEGORY_ENUM NOT NULL,
    director VARCHAR(200) NOT NULL,
    nationality VARCHAR(50) NOT NULL,
    rate DECIMAL(2, 1) NOT NULL,
    synopsis VARCHAR(600),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);